/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrustedFacilityIndexRouteImport } from './routes/trusted-facility/index'
import { Route as ComplexAsphaltingIndexRouteImport } from './routes/complex-asphalting/index'
import { Route as AsphaltConcreteMixIndexRouteImport } from './routes/asphalt-concrete-mix/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustedFacilityIndexRoute = TrustedFacilityIndexRouteImport.update({
  id: '/trusted-facility/',
  path: '/trusted-facility/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplexAsphaltingIndexRoute = ComplexAsphaltingIndexRouteImport.update({
  id: '/complex-asphalting/',
  path: '/complex-asphalting/',
  getParentRoute: () => rootRouteImport,
} as any)
const AsphaltConcreteMixIndexRoute = AsphaltConcreteMixIndexRouteImport.update({
  id: '/asphalt-concrete-mix/',
  path: '/asphalt-concrete-mix/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asphalt-concrete-mix/': typeof AsphaltConcreteMixIndexRoute
  '/complex-asphalting/': typeof ComplexAsphaltingIndexRoute
  '/trusted-facility/': typeof TrustedFacilityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asphalt-concrete-mix': typeof AsphaltConcreteMixIndexRoute
  '/complex-asphalting': typeof ComplexAsphaltingIndexRoute
  '/trusted-facility': typeof TrustedFacilityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asphalt-concrete-mix/': typeof AsphaltConcreteMixIndexRoute
  '/complex-asphalting/': typeof ComplexAsphaltingIndexRoute
  '/trusted-facility/': typeof TrustedFacilityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asphalt-concrete-mix/'
    | '/complex-asphalting/'
    | '/trusted-facility/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asphalt-concrete-mix'
    | '/complex-asphalting'
    | '/trusted-facility'
  id:
    | '__root__'
    | '/'
    | '/asphalt-concrete-mix/'
    | '/complex-asphalting/'
    | '/trusted-facility/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsphaltConcreteMixIndexRoute: typeof AsphaltConcreteMixIndexRoute
  ComplexAsphaltingIndexRoute: typeof ComplexAsphaltingIndexRoute
  TrustedFacilityIndexRoute: typeof TrustedFacilityIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trusted-facility/': {
      id: '/trusted-facility/'
      path: '/trusted-facility'
      fullPath: '/trusted-facility/'
      preLoaderRoute: typeof TrustedFacilityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complex-asphalting/': {
      id: '/complex-asphalting/'
      path: '/complex-asphalting'
      fullPath: '/complex-asphalting/'
      preLoaderRoute: typeof ComplexAsphaltingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asphalt-concrete-mix/': {
      id: '/asphalt-concrete-mix/'
      path: '/asphalt-concrete-mix'
      fullPath: '/asphalt-concrete-mix/'
      preLoaderRoute: typeof AsphaltConcreteMixIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsphaltConcreteMixIndexRoute: AsphaltConcreteMixIndexRoute,
  ComplexAsphaltingIndexRoute: ComplexAsphaltingIndexRoute,
  TrustedFacilityIndexRoute: TrustedFacilityIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
